version: '3'

volumes:
  local_mongo_data: {}

services: 
  nestjs:
    build:
      context: ./nestjs
      dockerfile: ./Dockerfile
    ports:
      - "0.0.0.0:7000:3000"
    volumes:
      - ./backend-service:/usr/src/app
    depends_on: 
      - mongodb
  
  reactjs:
    build: 
      context: ./reactjs
      dockerfile: ./Dockerfile
    ports:
      - "0.0.0.0:5000:3000"
    volumes: 
      - ./client-service:/app

  mongodb:
    ports:
      - "0.0.0.0:27018:27017"
    volumes:
      - local_mongo_data:/var/lib/mongodb/data
    image: mongo